### ISSUE TITLE
rule viewing of untouched rules is broken

### ISSUE THREAD

**Issue by lambits** [CritteRo/crit-phone#2]
haven't touched the moreApps file, and this is what a rule section looks like
![image](https://user-images.githubusercontent.com/48295237/146679077-255f8310-503b-443d-81cd-cd6990475e17.png)

**Comment by CritteRo** [comment]
I suspect I changed app ids at one point, and forgot to change in all places.

**Comment by CritteRo** [comment]
Fixed in b877353b1a318e4cb252abc0309230ed1db8d78e
